### ISSUE TITLE
Add convenience RNGs

### ISSUE THREAD

**Issue by ociaw** [ociaw/RandN#1]
We need to add wrapper RNGs with easy to understand names, so people don't have to trawl through the Rngs namespace and figure out the difference between ChaCha and Mersenne Twister. None of these need to be reproducible, since in that case the user will have to figure out which algorithm they want anyway.

[Rand](https://github.com/rust-random/rand) provides 4 different RNGs, 
- OsRng is an interface to the operating system's random number source.
- ThreadRng is a handle to a thread-local CSPRNG with periodic seeding from OsRng.
- StdRng is a CSPRNG chosen for good performance and trust of security.
- SmallRng is an insecure PRNG designed to be fast, simple, require little memory, and have good output quality.

We'll treat CryptoServiceProvider as similar enough OsRng, so there's no need to reimplement it. ChaCha is a good fit for StdRng, just need to decide how many rounds. ThreadLocal can be used to create an equivalent of ThreadRng through StdRng. PCG32 is a good candidate for SmallRng, though some statistical quality issues have been found recently.

Type names are TBD - SmallRng/FastRng/InsecureRng, StdRng/StandardRng/Rng, ThreadRng/ThreadLocalRng?

**Comment by peteroupc** [comment]
In general, if reproducibility is not important, the wrapper RNGs should be based on a [cryptographic RNG](https://peteroupc.github.io/random.html#Cryptographic_RNGs).

In this sense, take the example of PHP 7.0, which added the simple functions `random_bytes` and `random_int` that use cryptographic RNGs.

**Comment by ociaw** [comment]
That's why I plan on using ChaCha for StdRng. The number of rounds needs to be decided; I'm leaning towards 8 rounds for speed, though 20 rounds would be less risky in case ChaCha is weakened. 12 might be a good compromise.

SmallRng is specifically meant to have a small amount of state and be fast, so a CSRNG is not desirable.

**Comment by ociaw** [comment]
aa1f010aacb06d1f113354387f287fdb0a06b8ed adds ThreadLocalRng using ChaCha8, and 07a17238b86c45d9d3968a395e79ead66fdc0b38 adds StandardRng and SmallRng, using ChaCha8 and Pcg32 respectively.
